### ISSUE TITLE
Thread the graphics pipeline.

### ISSUE THREAD

**Issue by loicmorvan** [loicmorvan/Phoenix#11]

**Comment by loicmorvan** [comment]
![copy of data](https://user-images.githubusercontent.com/678628/30564428-32cb59b2-9cc5-11e7-9b67-9bbd97faaa9a.png)

**Comment by JacquesDiringer** [comment]
To answer your blue question: maybe instead of copying the data (and thus blocking the two threads in the meantime) you could do some double buffering ?
